use russh::{
    client,
    keys::{
        agent::{client::AgentClient, AgentIdentity}, decode_secret_key, PrivateKeyWithHashAlg,
    },
    ChannelMsg,
};

use std::collections::HashMap;
use std::sync::{
    atomic::{AtomicBool, Ordering},
    Arc,
};
use tauri::{AppHandle, Emitter, Manager, State};
use tokio::sync::{mpsc, Mutex, RwLock};

type SharedSshHandle = Arc<Mutex<client::Handle<known_hosts::ClientHandler>>>;
type LocalAgentStream = Box<dyn russh::keys::agent::client::AgentStream + Send + Unpin + 'static>;
pub(super) const SSH_TRANSFER_PROGRESS_EVENT: &str = "ssh-transfer-progress";
pub(super) const TRANSFER_CHUNK_SIZE: usize = 64 * 1024;
pub(super) const TRANSFER_PROGRESS_EMIT_STEP: u64 = 256 * 1024;
const AURATERM_RECONNECT_SESSION_PREFIX: &str = "at-";
pub(super) const SSH_KNOWN_HOSTS_FILE: &str = "ssh_known_hosts.json";
pub(super) const SECURITY_AUDIT_LOG_FILE: &str = "security_audit.log";

#[cfg(unix)]
pub(super) async fn connect_local_agent_stream() -> Result<LocalAgentStream, String> {
    AgentClient::<tokio::net::UnixStream>::connect_env()
        .await
        .map(AgentClient::into_inner)
        .map_err(|error| format!("SSH agent unavailable: {error}"))
}

#[cfg(windows)]
pub(super) async fn connect_local_agent_stream() -> Result<LocalAgentStream, String> {
    use tokio::net::windows::named_pipe::NamedPipeClient;

    let pipe = std::env::var_os("SSH_AUTH_SOCK")
        .unwrap_or_else(|| std::ffi::OsString::from(r"\\.\pipe\openssh-ssh-agent"));
    if let Ok(client) = AgentClient::<NamedPipeClient>::connect_named_pipe(pipe).await {
        return Ok(client.into_inner());
    }

    AgentClient::connect_pageant()
        .await
        .map(AgentClient::into_inner)
        .map_err(|error| format!("OpenSSH agent and Pageant are unavailable: {error}"))
}

mod types;
mod known_hosts;
mod transfer;
mod forwarding;

// Types consumed externally (`main.rs`, frontend payloads) are re-exported at
// the module root. A few of them (`SshHostKeyMismatchPromptPayload`,
// `TrustedSshHostKeyEntry`) are only used inside the `known_hosts` submodule
// and from outside the crate, so they trigger `unused_imports` inside this
// specific module — hence the allow attribute.
#[allow(unused_imports)]
pub use types::{
    AutoLoginRule, GeneratedSshKeyPair, JumpHostConfig, KeyboardInteractivePromptPayload, PtyExitPayload, ReconnectSessionPromptPayload,
    RemoteDirectoryListing, RemoteFileEntry, SshHostKeyMismatchPromptPayload, SshMfaPrompt,
    SshTransferDirection, SshTransferMode, SshTransferProgressPayload, SshTransferStatus,
    TerminalDataPayload, TrustedSshHostKeyEntry,
};
use types::InteractiveWriteOutcome;

// Re-export all tauri commands from the `known_hosts` submodule. A glob
// re-export is required so that the `__cmd__*` helper items generated by
// `#[tauri::command]` are also reachable as `ssh::__cmd__<name>`, which is
// how the `tauri::generate_handler!` macro expands references.
pub use known_hosts::*;
// Same rationale for the transfer submodule: `tauri::generate_handler!` needs
// to see `ssh::__cmd__<name>` for each `#[tauri::command]`.
pub use transfer::*;
// Port-forwarding / tunnel manager commands + `ForwardingState` (managed in
// `main.rs`). Glob re-export so `generate_handler!` resolves `ssh::__cmd__*`.
pub use forwarding::*;

#[tauri::command]
pub fn ssh_generate_key_pair(
    passphrase: Option<String>,
    comment: Option<String>,
) -> Result<GeneratedSshKeyPair, String> {
    use russh::keys::{Algorithm, HashAlg, PrivateKey};
    use ssh_key::LineEnding;

    let mut rng = russh::keys::key::safe_rng();
    let mut key = PrivateKey::random(&mut rng, Algorithm::Ed25519)
        .map_err(|error| format!("Failed to generate Ed25519 key: {error}"))?;
    let comment = comment
        .map(|value| value.trim().to_string())
        .filter(|value| !value.is_empty());
    if let Some(comment) = &comment {
        key.set_comment(comment);
    }
    if let Some(passphrase) = passphrase.filter(|value| !value.is_empty()) {
        key = key.encrypt(&mut rng, passphrase.as_bytes())
            .map_err(|error| format!("Failed to encrypt private key: {error}"))?;
    }

    let private_key = key.to_openssh(LineEnding::LF)
        .map_err(|error| format!("Failed to encode private key: {error}"))?
        .to_string();
    let mut public = key.public_key().clone();
    if let Some(comment) = comment {
        public.set_comment(comment);
    }
    let public_key = public.to_openssh()
        .map_err(|error| format!("Failed to encode public key: {error}"))?;
    let fingerprint = public.fingerprint(HashAlg::Sha256).to_string();
    Ok(GeneratedSshKeyPair { private_key, public_key, fingerprint })
}


/// Per-session state consolidated into a single record.
///
/// Previously these fields lived in eight separate `Arc<Mutex<HashMap>>`s,
/// which produced significant lock contention on the keystroke hot path
/// (`write_ssh_pty_input`) and on the IO loop's teardown. We now store the
/// whole per-id record in a single `Arc<RwLock<HashMap<String, SshSessionState>>>`:
///
/// - Hot-path readers (keystroke / resize dispatch) acquire a `read()` lock,
///   clone the cheap `mpsc::Sender` they need, and release the lock before
///   awaiting on the channel `.send()`. Because `Sender` is `Clone` and just
///   bumps an Arc refcount, the read section is O(1) and non-blocking.
/// - Low-frequency mutators (session insert/remove, reconnect metadata
///   update) take a `write()` lock only briefly.
#[derive(Default)]
pub struct SshSessionState {
    /// PTY input forwarder — the channel whose receiver feeds the IO loop.
    input_tx: Option<mpsc::Sender<Vec<u8>>>,
    /// Window-resize forwarder.
    resize_tx: Option<mpsc::Sender<(u32, u32)>>,
    /// MFA / keyboard-interactive answer forwarder.
    auth_tx: Option<mpsc::Sender<String>>,
    /// Reconnect-session-name picker response forwarder.
    reconnect_prompt_tx: Option<mpsc::Sender<Option<String>>>,
    /// Host-key mismatch trust decision forwarder.
    host_key_prompt_tx: Option<mpsc::Sender<bool>>,
    /// Underlying russh handle shared across PTY / SFTP / kill paths.
    handle: Option<SharedSshHandle>,
    /// When `Some`, an auto-reconnect loop is active; notifying it stops the loop.
    reconnect_flag: Option<Arc<ReconnectCancellation>>,
    /// When `Some`, auto-reconnect is enabled and this config is used on every retry.
    reconnect_config: Option<ReconnectConfig>,
    /// Per-session remote (`-R`) forward registry, shared with the russh
    /// `ClientHandler`. Created lazily and reused across reconnects so the
    /// handler always sees the same map.
    remote_forwards: Option<forwarding::RemoteForwardRegistry>,
}

#[derive(Default)]
struct ReconnectCancellation {
    cancelled: AtomicBool,
    notify: Arc<tokio::sync::Notify>,
}

impl ReconnectCancellation {
    fn cancel(&self) {
        self.cancelled.store(true, Ordering::Release);
        self.notify.notify_waiters();
    }

    fn is_cancelled(&self) -> bool {
        self.cancelled.load(Ordering::Acquire)
    }
}

#[derive(Clone)]
pub struct SshState {
    /// Single source of truth for every live SSH session, keyed by the
    /// frontend-assigned connection id.
    sessions: Arc<RwLock<HashMap<String, SshSessionState>>>,
    hub: Arc<crate::terminal_event_hub::TerminalEventHub>,
}

#[derive(Clone)]
struct ReconnectConfig {
    host: String,
    port: u16,
    user: String,
    password: Option<String>,
    private_key: Option<String>,
    passphrase: Option<String>,
    auth_type: Option<String>,
    agent_forwarding: bool,
    jump_hosts: Vec<JumpHostConfig>,
    auto_login_rules: Vec<AutoLoginRule>,
    post_connect_commands: Vec<String>,
    reconnect_type: ReconnectType,
    session_name: String,
    checked_existing_sessions: bool,
    cols: u32,
    rows: u32,
    last_error: Option<String>,
}

#[derive(Clone, Copy, Debug, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ReconnectType {
    /// Manual reconnect: after disconnect the user can trigger a new connection from the UI.
    Manual,
    /// Reconnect only: no server-side session manager. Running tasks will be lost on disconnect.
    Simple,
    Screen,
    Tmux,
}

impl Default for SshState {
    fn default() -> Self {
        Self::new(Arc::new(crate::terminal_event_hub::TerminalEventHub::new()))
    }
}

impl SshState {
    pub fn new(hub: Arc<crate::terminal_event_hub::TerminalEventHub>) -> Self {
        Self {
            sessions: Arc::new(RwLock::new(HashMap::new())),
            hub,
        }
    }

    pub async fn contains(&self, id: &str) -> bool {
        self.input_sender(id).await.is_some()
    }

    pub async fn write_bytes(&self, id: &str, data: &[u8]) -> Result<(), String> {
        let tx = self.input_sender(id).await.ok_or_else(|| "Connection not found".to_string())?;
        tx.send(data.to_vec()).await.map_err(|_| "SSH connection lost; bytes were not sent".to_string())
    }

    /// Return a snapshot clone of `T` extracted from the session at `id`,
    /// holding only a read lock during the extraction. Used on hot paths.
    async fn snapshot<T, F>(&self, id: &str, f: F) -> Option<T>
    where
        F: FnOnce(&SshSessionState) -> Option<T>,
    {
        let guard = self.sessions.read().await;
        guard.get(id).and_then(f)
    }

    /// Clone the cheap raw-byte sender for PTY input, if any.
    async fn input_sender(&self, id: &str) -> Option<mpsc::Sender<Vec<u8>>> {
        self.snapshot(id, |s| s.input_tx.clone()).await
    }

    /// Clone the cheap `mpsc::Sender<(u32, u32)>` for window resize, if any.
    async fn resize_sender(&self, id: &str) -> Option<mpsc::Sender<(u32, u32)>> {
        self.snapshot(id, |s| s.resize_tx.clone()).await
    }

    /// Clone the MFA response sender, if any.
    async fn auth_sender(&self, id: &str) -> Option<mpsc::Sender<String>> {
        self.snapshot(id, |s| s.auth_tx.clone()).await
    }

    /// Clone the reconnect-prompt response sender, if any.
    async fn reconnect_prompt_sender(
        &self,
        id: &str,
    ) -> Option<mpsc::Sender<Option<String>>> {
        self.snapshot(id, |s| s.reconnect_prompt_tx.clone()).await
    }

    /// Clone the host-key-prompt response sender, if any.
    async fn host_key_prompt_sender(&self, id: &str) -> Option<mpsc::Sender<bool>> {
        self.snapshot(id, |s| s.host_key_prompt_tx.clone()).await
    }

    /// Clone the underlying russh handle, if any.
    async fn handle(&self, id: &str) -> Option<SharedSshHandle> {
        self.snapshot(id, |s| s.handle.clone()).await
    }

    /// Clone the reconnect config, if any.
    async fn reconnect_config(&self, id: &str) -> Option<ReconnectConfig> {
        self.snapshot(id, |s| s.reconnect_config.clone()).await
    }

    /// Mutate an existing session record under the write lock. No-op if
    /// the session has already been cleaned up.
    async fn with_session_mut<F, R>(&self, id: &str, f: F) -> Option<R>
    where
        F: FnOnce(&mut SshSessionState) -> R,
    {
        let mut guard = self.sessions.write().await;
        guard.get_mut(id).map(f)
    }

    /// Ensure a session record exists and apply a mutation closure.
    async fn upsert_session<F>(&self, id: &str, f: F)
    where
        F: FnOnce(&mut SshSessionState),
    {
        let mut guard = self.sessions.write().await;
        let entry = guard.entry(id.to_string()).or_default();
        f(entry);
    }

    /// Get (or lazily create) the per-session remote-forward registry. Used both
    /// by the connect path (handed to the `ClientHandler`) and by the tunnel
    /// commands when registering a remote (`-R`) forward target.
    async fn ensure_remote_forwards(&self, id: &str) -> forwarding::RemoteForwardRegistry {
        let mut guard = self.sessions.write().await;
        let entry = guard.entry(id.to_string()).or_default();
        entry
            .remote_forwards
            .get_or_insert_with(forwarding::new_remote_forward_registry)
            .clone()
    }

    async fn ensure_remote_forwards_owned(self, id: String) -> forwarding::RemoteForwardRegistry {
        self.ensure_remote_forwards(&id).await
    }

    async fn upsert_session_owned<F>(self, id: String, f: F)
    where
        F: FnOnce(&mut SshSessionState) + Send,
    {
        self.upsert_session(&id, f).await;
    }

    /// Read-only access to the remote-forward registry, if one exists.
    async fn remote_forwards_opt(&self, id: &str) -> Option<forwarding::RemoteForwardRegistry> {
        let guard = self.sessions.read().await;
        guard.get(id).and_then(|s| s.remote_forwards.clone())
    }
}

fn shell_escape(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\"'\"'"))
}

fn build_screen_attach_command(session_name: &str) -> String {
    let escaped_session_name = shell_escape(session_name);
    let screen_term_candidates = [
        "screen.xterm-256color",
        "screen-256color",
        "screen",
        "xterm-256color",
        "vt100",
    ]
    .iter()
    .map(|candidate| shell_escape(candidate))
    .collect::<Vec<_>>()
    .join(" ");
    format!(
        concat!(
            "screen_term=''; ",
            "for candidate in {candidates}; do ",
            "if infocmp \"$candidate\" >/dev/null 2>&1 || TERM=\"$candidate\" tput longname >/dev/null 2>&1; then ",
            "screen_term=\"$candidate\"; break; ",
            "fi; ",
            "done; ",
            "[ -n \"$screen_term\" ] || screen_term='vt100'; ",
            "tmp_rc=$(mktemp /tmp/auraterm-screenrc.XXXXXX 2>/dev/null || mktemp -t auraterm-screenrc.XXXXXX) || exit 1; ",
            "printf '%s\\n%s\\n%s\\n%s\\n' \"term $screen_term\" 'termcapinfo xterm* ti@:te@' 'defscrollback 10000' 'escape ^Bb' > \"$tmp_rc\"; ",
            "printf '\\033[32m[AuraTerm] Screen mode: TERM=%s, wheel scroll and 10000 lines scrollback enabled. Escape key is Ctrl+B.\\033[0m\\n' \"$screen_term\"; ",
            "screen -S {sess} -X eval \"term $screen_term\" 'termcapinfo xterm* ti@:te@' 'defscrollback 10000' 'escape ^Bb' >/dev/null 2>&1 || true; ",
            "screen -T \"$screen_term\" -dr {sess} 2>/dev/null || screen -c \"$tmp_rc\" -T \"$screen_term\" -S {sess}; ",
            "status=$?; rm -f \"$tmp_rc\"; exit $status"
        ),
        sess = escaped_session_name,
        candidates = screen_term_candidates,
    )
}

/// Build the remote command that attaches to (or creates) the tmux session used
/// for reconnect persistence, then enables mouse scrolling. Attaching to an
/// existing session is preferred so a reconnect rejoins the live shell.
fn build_tmux_attach_command(session_name: &str) -> String {
    let sess = shell_escape(session_name);
    format!(
        "tmux new-session -A -s {sess} 2>/dev/null || tmux attach-session -t {sess} 2>/dev/null || tmux new-session -s {sess}; tmux set -g mouse on 2>/dev/null; true"
    )
}

fn auraterm_reconnect_session_name(id: &str) -> String {
    format!("{AURATERM_RECONNECT_SESSION_PREFIX}{id}")
}

/// Clear all transient channels/handles for a session while keeping the
/// reconnect config and reconnect flag (so auto-reconnect can restart).
async fn cleanup_ssh_runtime_state(state: &SshState, id: &str) {
    state
        .with_session_mut(id, |s| {
            s.input_tx = None;
            s.resize_tx = None;
            s.auth_tx = None;
            s.handle = None;
            s.reconnect_prompt_tx = None;
            s.host_key_prompt_tx = None;
        })
        .await;
}

/// Clear transient state plus the reconnect config. Auto-reconnect flag is
/// preserved so the reconnect loop can observe cancellation.
async fn cleanup_ssh_session(state: &SshState, id: &str) {
    state
        .with_session_mut(id, |s| {
            s.input_tx = None;
            s.resize_tx = None;
            s.auth_tx = None;
            s.handle = None;
            s.reconnect_prompt_tx = None;
            s.host_key_prompt_tx = None;
            s.reconnect_config = None;
        })
        .await;
    // Do NOT clear reconnect_flag here — that's handled only in close_ssh_pty
    // to allow the reconnect loop to restart the connection.
}

/// Stop reconnect loop for a session and clean up all state, finally dropping
/// the entire session record.
async fn stop_and_cleanup_ssh_session(state: &SshState, id: &str) {
    // Signal the reconnect loop to stop, then remove the session entirely.
    let notify = {
        let mut guard = state.sessions.write().await;
        let notify = guard
            .get_mut(id)
            .and_then(|s| s.reconnect_flag.take());
        guard.remove(id);
        notify
    };
    if let Some(notify) = notify {
        notify.cancel();
    }
}

async fn get_ssh_handle(state: &SshState, id: &str) -> Result<SharedSshHandle, String> {
    state
        .handle(id)
        .await
        .ok_or_else(|| "SSH session is not ready yet".to_string())
}

async fn set_reconnect_session_metadata(
    state: SshState,
    id: String,
    session_name: Option<String>,
    checked_existing_sessions: Option<bool>,
) {
    state
        .with_session_mut(&id, |s| {
            if let Some(config) = s.reconnect_config.as_mut() {
                if let Some(name) = session_name {
                    config.session_name = name;
                }
                if let Some(checked) = checked_existing_sessions {
                    config.checked_existing_sessions = checked;
                }
            }
        })
        .await;
}

async fn open_ssh_channel(
    state: &SshState,
    id: &str,
) -> Result<russh::Channel<client::Msg>, String> {
    let handle = get_ssh_handle(state, id).await?;
    let guard = handle.lock().await;
    guard
        .channel_open_session()
        .await
        .map_err(|error| format!("Failed to open SSH channel: {error}"))
}


#[tauri::command]
pub async fn answer_ssh_mfa(
    state: State<'_, SshState>,
    id: String,
    responses: Vec<String>,
) -> Result<(), String> {
    // Clone the sender under the read lock so the mpsc awaits run lock-free.
    let tx = state
        .auth_sender(&id)
        .await
        .ok_or_else(|| "Auth response channel not found".to_string())?;
    for response in responses {
        tx.send(response)
            .await
            .map_err(|_| "Failed to send MFA response".to_string())?;
    }
    Ok(())
}

#[tauri::command]
pub async fn answer_ssh_reconnect_choice(
    state: State<'_, SshState>,
    id: String,
    session_name: Option<String>,
) -> Result<(), String> {
    let tx = state
        .reconnect_prompt_sender(&id)
        .await
        .ok_or_else(|| "Reconnect prompt channel not found".to_string())?;

    tx.send(session_name.filter(|value| !value.trim().is_empty()))
        .await
        .map_err(|_| "Failed to send reconnect choice".to_string())
}

#[tauri::command]
pub async fn answer_ssh_host_key_mismatch(
    state: State<'_, SshState>,
    id: String,
    trust_new_fingerprint: bool,
) -> Result<(), String> {
    let tx = state
        .host_key_prompt_sender(&id)
        .await
        .ok_or_else(|| "Host key prompt channel not found".to_string())?;

    tx.send(trust_new_fingerprint)
        .await
        .map_err(|_| "Failed to send host key decision".to_string())
}

#[tauri::command]
pub async fn rename_ssh_session(
    state: State<'_, SshState>,
    id: String,
    new_name: String,
) -> Result<(), String> {
    let new_name = new_name.trim().to_string();
    if new_name.is_empty() {
        return Err("New session name cannot be empty".to_string());
    }

    let (old_name, reconnect_type) = state
        .reconnect_config(&id)
        .await
        .map(|c| (c.session_name.clone(), c.reconnect_type))
        .ok_or_else(|| "SSH session not found or not in reconnect mode".to_string())?;

    if old_name == new_name {
        return Ok(());
    }

    let rename_cmd = match reconnect_type {
        ReconnectType::Tmux => format!(
            "tmux rename-session -t {} {} 2>/dev/null || true",
            shell_escape(&old_name),
            shell_escape(&new_name),
        ),
        ReconnectType::Screen => format!(
            "screen -S {} -X sessionname {} 2>/dev/null; true",
            shell_escape(&old_name),
            shell_escape(&new_name),
        ),
        _ => return Err("Session is not in screen/tmux mode".to_string()),
    };

    let handle = get_ssh_handle(&state, &id).await?;
    run_remote_command_capture(handle, rename_cmd).await?;

    state
        .with_session_mut(&id, |s| {
            if let Some(config) = s.reconnect_config.as_mut() {
                config.session_name = new_name;
            }
        })
        .await;

    Ok(())
}

#[tauri::command]
pub async fn write_ssh_pty_input(
    app: AppHandle,
    state: State<'_, SshState>,
    id: String,
    data: String,
) -> Result<(), String> {
    // Hot path: acquire the read lock only long enough to clone the cheap
    // mpsc::Sender, then drop the lock before awaiting on `.send()`. This
    // lets concurrent keystrokes and IO-loop teardown proceed in parallel.
    let tx = state.input_sender(&id).await;

    if let Some(tx) = tx {
        if tx.send(data.into_bytes()).await.is_err() {
            let message = "SSH connection lost; input was not sent".to_string();
            let _ = app.emit(
                &crate::util::session_event("pty-output", &id),
                TerminalDataPayload {
                    id,
                    data: format!("\r\n\x1b[31m[{message}]\x1b[0m\r\n"),
                },
            );
            Err(message)
        } else {
            Ok(())
        }
    } else {
        Err("Connection not found".to_string())
    }
}

#[tauri::command]
pub async fn write_ssh_pty_bytes(
    state: State<'_, SshState>,
    id: String,
    data: Vec<u8>,
) -> Result<(), String> {
    let tx = state.input_sender(&id).await.ok_or_else(|| "Connection not found".to_string())?;
    tx.send(data).await.map_err(|_| "SSH connection lost; bytes were not sent".to_string())
}

#[tauri::command]
pub async fn resize_ssh_pty(
    state: State<'_, SshState>,
    id: String,
    cols: u32,
    rows: u32,
) -> Result<(), String> {
    // Clone the sender under a read lock so `.send()` happens lock-free.
    let tx = state
        .resize_sender(&id)
        .await
        .ok_or_else(|| "Connection not found".to_string())?;
    let _ = tx.send((cols, rows)).await;
    Ok(())
}

#[tauri::command]
pub async fn close_ssh_pty(
    state: State<'_, SshState>,
    forwarding: State<'_, ForwardingState>,
    zmodem: State<'_, crate::zmodem::ZmodemState>,
    id: String,
) -> Result<(), String> {
    // Tear down any port forwards bound to this session before the handle dies.
    forwarding::stop_session_tunnels(forwarding.inner(), &id).await;
    zmodem.reset_session(&id);

    // For session-persistence modes (tmux/screen), try to destroy the remote session first.
    let config = state.reconnect_config(&id).await;
    if let Some(cfg) = config {
        let kill_cmd = match cfg.reconnect_type {
            ReconnectType::Manual => None,
            ReconnectType::Simple => None,
            ReconnectType::Tmux => Some(format!(
                "tmux kill-session -t {} 2>/dev/null; exit 0",
                shell_escape(&cfg.session_name)
            )),
            ReconnectType::Screen => Some(format!(
                "screen -S {} -X quit 2>/dev/null; exit 0",
                shell_escape(&cfg.session_name)
            )),
        };
        if let Some(cmd) = kill_cmd {
            if let Ok(handle) = get_ssh_handle(state.inner(), &id).await {
                // Best-effort: open a channel, run the kill command, ignore errors.
                let _ = async {
                    let guard = handle.lock().await;
                    let channel = guard.channel_open_session().await?;
                    channel.exec(true, cmd).await?;
                    // Drain until EOF so the server has time to process the command.
                    let mut ch = channel;
                    loop {
                        match ch.wait().await {
                            Some(ChannelMsg::Eof) | Some(ChannelMsg::Close) | None => break,
                            _ => {}
                        }
                    }
                    Ok::<_, russh::Error>(())
                }.await;
            }
        }
    }
    stop_and_cleanup_ssh_session(state.inner(), &id).await;
    Ok(())
}

/// Authenticate an SSH session and return a connected handle.
fn authenticate_ssh(
    host: String,
    port: u16,
    user: String,
    password: Option<String>,
    private_key: Option<String>,
    passphrase: Option<String>,
    auth_type: Option<String>,
    agent_forwarding: bool,
    jump_hosts: Vec<JumpHostConfig>,
    app: AppHandle,
    id: String,
    auth_response_rx: &mut mpsc::Receiver<String>,
    remote_forwards: forwarding::RemoteForwardRegistry,
) -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<SharedSshHandle, String>> + Send + '_>> {
    Box::pin(async move {
    let mut current: Option<SharedSshHandle> = None;

    for jump in jump_hosts {
        let (mut session, observed) = if let Some(previous) = current.as_ref() {
            let channel = open_proxy_channel(previous.clone(), jump.host.clone(), jump.port).await?;
            known_hosts::connect_stream_with_expected_fingerprint(
                channel.into_stream(),
                None,
                forwarding::new_remote_forward_registry(),
                false,
            )
            .await
            .map_err(|(error, _)| error)?
        } else {
            known_hosts::connect_with_expected_fingerprint(
                jump.host.clone(),
                jump.port,
                None,
                forwarding::new_remote_forward_registry(),
                false,
            )
            .await
            .map_err(|(error, _)| error)?
        };

        verify_host_fingerprint(app.clone(), id.clone(), jump.host.clone(), jump.port, observed).await?;
        session = authenticate_connected_session(
            session,
            jump.user.clone(),
            Some(jump.auth_type.clone()),
            jump.password.clone(),
            jump.private_key.clone(),
            jump.passphrase.clone(),
            app.clone(),
            id.clone(),
            auth_response_rx,
        )
        .await
        .map_err(|error| format!("ProxyJump {}@{}:{}: {error}", jump.user, jump.host, jump.port))?;
        current = Some(Arc::new(Mutex::new(session)));
    }

    let (mut session, observed) = if let Some(previous) = current.as_ref() {
        let channel = open_proxy_channel(previous.clone(), host.clone(), port).await?;
        known_hosts::connect_stream_with_expected_fingerprint(
            channel.into_stream(),
            None,
            remote_forwards,
            agent_forwarding,
        )
        .await
        .map_err(|(error, _)| error)?
    } else {
        known_hosts::connect_with_expected_fingerprint(
            host.clone(),
            port,
            None,
            remote_forwards,
            agent_forwarding,
        )
        .await
        .map_err(|(error, _)| error)?
    };

    verify_host_fingerprint(app.clone(), id.clone(), host.clone(), port, observed).await?;
    session = authenticate_connected_session(
        session,
        user,
        auth_type,
        password,
        private_key,
        passphrase,
        app,
        id,
        auth_response_rx,
    )
    .await?;

    Ok(Arc::new(Mutex::new(session)))
    })
}

async fn open_proxy_channel(
    handle: SharedSshHandle,
    host: String,
    port: u16,
) -> Result<russh::Channel<client::Msg>, String> {
    let guard = handle.lock().await;
    guard
        .channel_open_direct_tcpip(host.clone(), port.into(), "127.0.0.1".to_string(), 0)
        .await
        .map_err(|error| format!("ProxyJump channel to {host}:{port} failed: {error}"))
}

async fn verify_host_fingerprint(
    app: AppHandle,
    id: String,
    host: String,
    port: u16,
    observed: Option<String>,
) -> Result<(), String> {
    let observed = observed.ok_or_else(|| format!("SSH server {host}:{port} did not present a host key"))?;
    let scope = known_hosts::known_host_scope(&host, port);
    let mut store = known_hosts::load_known_hosts(&app).await?;

    if let Some(expected) = store.hosts.get(&scope).cloned() {
        if expected == observed {
            return Ok(());
        }
        let trust = known_hosts::prompt_for_host_key_override(
            &app,
            app.state::<SshState>().inner().clone(),
            &id,
            &host,
            port,
            &expected,
            &observed,
        )
        .await?;
        if !trust {
            return Err(format!("SSH host key changed for {scope}. Connection cancelled by user."));
        }
        known_hosts::append_host_key_override_audit_log(&app, &host, port, &expected, &observed).await?;
    }

    store.hosts.insert(scope, observed);
    known_hosts::save_known_hosts(&app, &store).await
}

#[allow(clippy::too_many_arguments)]
fn authenticate_connected_session(
    mut session: client::Handle<known_hosts::ClientHandler>,
    user: String,
    auth_type: Option<String>,
    password: Option<String>,
    private_key: Option<String>,
    passphrase: Option<String>,
    app: AppHandle,
    id: String,
    auth_response_rx: &mut mpsc::Receiver<String>,
) -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<client::Handle<known_hosts::ClientHandler>, String>> + Send + '_>> {
    Box::pin(async move {
    let password = password.filter(|value| !value.is_empty());
    let private_key = private_key.filter(|value| !value.trim().is_empty());
    let method = auth_type.unwrap_or_else(|| {
        if private_key.is_some() { "key".to_string() }
        else if password.is_some() { "password".to_string() }
        else { "none".to_string() }
    });

    let interactive = match method.as_str() {
        "key" => {
            let key = private_key.ok_or_else(|| "Private key is required".to_string())?;
            let decoded = decode_secret_key(&key, passphrase.as_deref().filter(|value| !value.is_empty()))
                .map_err(|error| format!("Private key parse error: {error}"))?;
            let rsa_hash = session.best_supported_rsa_hash().await
                .map_err(|error| format!("Failed to determine RSA hash algorithm: {error}"))?
                .flatten();
            match session.authenticate_publickey(
                user.clone(),
                PrivateKeyWithHashAlg::new(Arc::new(decoded), rsa_hash),
            ).await {
                Ok(client::AuthResult::Success) => None,
                Ok(client::AuthResult::Failure { .. }) => return Err("Private key authentication failed".to_string()),
                Err(error) => return Err(format!("Private key auth error: {error}")),
            }
        }
        "agent" => {
            return authenticate_with_agent(session, user).await;
        }
        "password" => {
            let password = password.ok_or_else(|| "Password is required".to_string())?;
            match session.authenticate_password(user.clone(), password).await {
                Ok(client::AuthResult::Success) => None,
                Ok(client::AuthResult::Failure { .. }) => {
                    Some(session.authenticate_keyboard_interactive_start(user.clone(), None).await)
                }
                Err(error) => return Err(format!("Password auth error: {error}")),
            }
        }
        "none" => Some(session.authenticate_keyboard_interactive_start(user.clone(), None).await),
        other => return Err(format!("Unsupported SSH auth type: {other}")),
    };

    if let Some(result) = interactive {
        run_keyboard_interactive(&mut session, result, app, id, auth_response_rx).await?;
    }
    Ok(session)
    })
}

fn authenticate_with_agent(
    mut session: client::Handle<known_hosts::ClientHandler>,
    user: String,
) -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<client::Handle<known_hosts::ClientHandler>, String>> + Send>> {
    Box::pin(async move {
    let stream = connect_local_agent_stream().await?;
    let mut agent = AgentClient::connect(stream);
    let identities = agent.request_identities().await
        .map_err(|error| format!("Failed to list SSH agent identities: {error}"))?;
    if identities.is_empty() {
        return Err("SSH agent has no identities".to_string());
    }
    let rsa_hash = session.best_supported_rsa_hash().await
        .map_err(|error| format!("Failed to determine RSA hash algorithm: {error}"))?
        .flatten();

    for identity in identities {
        let key = match identity {
            AgentIdentity::PublicKey { key, .. } => key,
            AgentIdentity::Certificate { certificate, .. } => {
                russh::keys::PublicKey::new(certificate.public_key().clone(), "")
            }
        };
        // `authenticate_publickey_with` is generic over a `Signer` whose
        // signing future is RPITIT (`impl Future + Send`). Awaiting it directly
        // inside this boxed `Send` future trips a rustc higher-ranked-lifetime
        // limitation, so we box the call to erase the opaque type first.
        let auth: std::pin::Pin<Box<dyn std::future::Future<Output = Result<client::AuthResult, russh::AgentAuthError>> + Send>> =
            Box::pin(session.authenticate_publickey_with(user.clone(), key, rsa_hash, &mut agent));
        match auth.await {
            Ok(client::AuthResult::Success) => return Ok(session),
            Ok(client::AuthResult::Failure { .. }) => continue,
            Err(error) => return Err(format!("SSH agent signing failed: {error}")),
        }
    }
    Err("SSH agent authentication failed for every identity".to_string())
    })
}

async fn run_keyboard_interactive(
    session: &mut client::Handle<known_hosts::ClientHandler>,
    result: Result<client::KeyboardInteractiveAuthResponse, russh::Error>,
    app: AppHandle,
    id: String,
    auth_response_rx: &mut mpsc::Receiver<String>,
) -> Result<(), String> {
    let mut response = result.map_err(|error| format!("Keyboard interactive init failed: {error}"))?;
    loop {
        match response {
            client::KeyboardInteractiveAuthResponse::Success => return Ok(()),
            client::KeyboardInteractiveAuthResponse::Failure { .. } => return Err("Authentication failed".to_string()),
            client::KeyboardInteractiveAuthResponse::InfoRequest { name, instructions, prompts } => {
                let payload = KeyboardInteractivePromptPayload {
                    id: id.to_string(),
                    name,
                    instruction: instructions,
                    prompts: prompts.iter().map(|prompt| SshMfaPrompt {
                        text: prompt.prompt.clone(),
                        echo: prompt.echo,
                    }).collect(),
                };
                let _ = app.emit(&crate::util::session_event("ssh-mfa-prompt", &id), payload);
                let mut answers = Vec::with_capacity(prompts.len());
                for _ in &prompts {
                    answers.push(auth_response_rx.recv().await
                        .ok_or_else(|| "Failed to collect MFA response".to_string())?);
                }
                response = session.authenticate_keyboard_interactive_respond(answers).await
                    .map_err(|error| format!("Failed auth step: {error}"))?;
            }
        }
    }
}

/// Re-issue `tcpip-forward` requests for every registered remote (`-R`) forward
/// on a freshly connected handle. Used after a reconnect so server-side
/// listeners are recreated; best-effort, errors are ignored.
async fn reissue_remote_forwards(
    handle: SharedSshHandle,
    registry: forwarding::RemoteForwardRegistry,
) {
    let binds: Vec<(String, u32)> = match registry.lock() {
        Ok(map) => map
            .iter()
            .map(|(port, target)| (target.bind_address.clone(), *port))
            .collect(),
        Err(_) => return,
    };
    if binds.is_empty() {
        return;
    }
    let guard = handle.lock().await;
    for (bind_address, bind_port) in binds {
        let _ = guard.tcpip_forward(bind_address, bind_port).await;
    }
}

/// Check whether a command exists on the remote host.
async fn run_remote_command_capture(handle: SharedSshHandle, command: String) -> Result<String, String> {
    let Ok(channel) = ({
        let guard = handle.lock().await;
        guard.channel_open_session().await
    }) else {
        return Err("Failed to open remote command channel".to_string());
    };

    channel
        .exec(true, command)
        .await
        .map_err(|error| format!("Remote command failed: {error}"))?;

    let mut output = String::new();
    let mut ch = channel;
    loop {
        match ch.wait().await {
            Some(ChannelMsg::Data { ref data }) | Some(ChannelMsg::ExtendedData { ref data, .. }) => {
                output.push_str(&String::from_utf8_lossy(data));
            }
            Some(ChannelMsg::Eof) | Some(ChannelMsg::Close) | None => break,
            _ => {}
        }
    }

    Ok(output)
}

async fn remote_command_exists(handle: SharedSshHandle, cmd: String) -> bool {
    let check_cmd = format!("command -v {} >/dev/null 2>&1 && echo __EXISTS__", cmd);
    match run_remote_command_capture(handle, check_cmd).await {
        Ok(output) => output.contains("__EXISTS__"),
        Err(_) => false,
    }
}

async fn list_detached_auraterm_sessions(
    handle: SharedSshHandle,
    reconnect_type: ReconnectType,
) -> Result<Vec<String>, String> {
    let output = match reconnect_type {
        ReconnectType::Manual => return Ok(vec![]),
        ReconnectType::Simple => return Ok(vec![]),
        ReconnectType::Tmux => run_remote_command_capture(
            handle.clone(),
            "tmux list-sessions -F '#{session_name} #{?session_attached,1,0}' 2>/dev/null || true".to_string(),
        )
        .await?,
        ReconnectType::Screen => run_remote_command_capture(
            handle,
            "screen -ls 2>/dev/null || true".to_string(),
        )
        .await?,
    };

    let mut sessions = match reconnect_type {
        ReconnectType::Manual => vec![],
        ReconnectType::Simple => vec![],
        ReconnectType::Tmux => output
            .lines()
            .filter_map(|line| {
                let mut parts = line.split_whitespace();
                let name = parts.next()?;
                let attached = parts.next()?;
                (attached == "0" && name.starts_with(AURATERM_RECONNECT_SESSION_PREFIX))
                    .then(|| name.to_string())
            })
            .collect::<Vec<_>>(),
        ReconnectType::Screen => output
            .lines()
            .filter(|line| line.contains("Detached"))
            .filter_map(|line| {
                let token = line.split_whitespace().next()?;
                let (_, name) = token.split_once('.')?;
                name.starts_with(AURATERM_RECONNECT_SESSION_PREFIX)
                    .then(|| name.to_string())
            })
            .collect::<Vec<_>>(),
    };

    sessions.sort();
    sessions.dedup();
    Ok(sessions)
}

async fn prompt_for_existing_reconnect_session(
    app: AppHandle,
    state: SshState,
    id: String,
    reconnect_type: ReconnectType,
    sessions: Vec<String>,
) -> Result<Option<String>, String> {
    if sessions.is_empty() {
        return Ok(None);
    }

    let (tx, mut rx) = mpsc::channel::<Option<String>>(1);
    state
        .upsert_session(&id, |s| s.reconnect_prompt_tx = Some(tx))
        .await;

    let tool = match reconnect_type {
        ReconnectType::Manual => "manual",
        ReconnectType::Simple => "simple",
        ReconnectType::Tmux => "tmux",
        ReconnectType::Screen => "screen",
    };

    if app
        .emit(
            &crate::util::session_event("ssh-reconnect-session-prompt", &id),
            ReconnectSessionPromptPayload {
                id: id.clone(),
                tool: tool.to_string(),
                sessions,
            },
        )
        .is_err()
    {
        state
            .with_session_mut(&id, |s| s.reconnect_prompt_tx = None)
            .await;
        return Ok(None);
    }

    let response = tokio::time::timeout(tokio::time::Duration::from_secs(120), rx.recv())
        .await
        .ok()
        .flatten()
        .flatten();

    state
        .with_session_mut(&id, |s| s.reconnect_prompt_tx = None)
        .await;
    Ok(response)
}

/// Open a PTY channel and attach/create a screen or tmux session.
/// For Manual/Simple mode or when the multiplexer is unavailable, falls back to a plain shell.
/// Returns (channel, used_multiplexer: bool).
async fn open_pty_channel(
    handle: SharedSshHandle,
    session_name: String,
    cols: u32,
    rows: u32,
    reconnect_type: Option<ReconnectType>,
    agent_forwarding: bool,
) -> Result<(russh::Channel<client::Msg>, bool), String> {
    let guard = handle.lock().await;
    let channel = guard
        .channel_open_session()
        .await
        .map_err(|error| format!("Channel error: {error}"))?;
    drop(guard);

    channel
        .request_pty(false, "xterm-256color", cols, rows, 0, 0, &[])
        .await
        .map_err(|error| format!("PTY request failed: {error}"))?;

    if agent_forwarding {
        channel
            .agent_forward(false)
            .await
            .map_err(|error| format!("Agent forwarding request failed: {error}"))?;
    }

    if let Some(rt) = reconnect_type {
        match rt {
            // Manual/Simple modes skip the multiplexer and go straight to the shell.
            ReconnectType::Manual => {}
            ReconnectType::Simple => {}
            ReconnectType::Tmux | ReconnectType::Screen => {
                let tool_name = match rt {
                    ReconnectType::Tmux => "tmux",
                    ReconnectType::Screen => "screen",
                    ReconnectType::Manual => unreachable!(),
                    ReconnectType::Simple => unreachable!(),
                };
                let tool_available = remote_command_exists(handle.clone(), tool_name.to_string()).await;

                if tool_available {
                    let attach_cmd = match rt {
                        ReconnectType::Tmux => build_tmux_attach_command(&session_name),
                        ReconnectType::Screen => build_screen_attach_command(&session_name),
                        ReconnectType::Manual => unreachable!(),
                        ReconnectType::Simple => unreachable!(),
                    };
                    channel
                        .exec(false, attach_cmd)
                        .await
                        .map_err(|error| format!("Failed to start {}: {error}", tool_name))?;
                    return Ok((channel, true));
                }
                // Tool not available — fall through to plain shell with a notice (written after returning).
            }
        }
    }

    // Plain shell fallback (Simple mode or multiplexer unavailable).
    channel
        .request_shell(true)
        .await
        .map_err(|error| format!("Shell request failed: {error}"))?;
    Ok((channel, false))
}

#[tauri::command]
pub async fn start_ssh_pty(
    app: AppHandle,
    state: State<'_, SshState>,
    zmodem: State<'_, crate::zmodem::ZmodemState>,
    id: String,
    host: String,
    port: u16,
    user: String,
    password: Option<String>,
    private_key: Option<String>,
    passphrase: Option<String>,
    auth_type: Option<String>,
    agent_forwarding: Option<bool>,
    jump_hosts: Option<Vec<JumpHostConfig>>,
    auto_login_rules: Option<Vec<AutoLoginRule>>,
    post_connect_commands: Option<Vec<String>>,
    cols: u32,
    rows: u32,
    auto_reconnect: Option<bool>,
    reconnect_type: Option<ReconnectType>,
) -> Result<(), String> {
    crate::debug_log!("Starting SSH connection to {}@{}:{}", user, host, port);

    // Stop any previous session for this id.
    stop_and_cleanup_ssh_session(state.inner(), &id).await;
    zmodem.reset_session(&id);

    let rt = reconnect_type.unwrap_or_else(|| {
        if auto_reconnect.unwrap_or(false) {
            ReconnectType::Simple
        } else {
            ReconnectType::Manual
        }
    });
    let use_reconnect = !matches!(rt, ReconnectType::Manual);

    // Always create a fresh auth-response channel registered under this id.
    let (auth_response_tx, auth_response_rx) = mpsc::channel::<String>(4);
    state
        .upsert_session(&id, |s| s.auth_tx = Some(auth_response_tx))
        .await;

    if use_reconnect {
        // Store reconnect configuration + cancellation notifier in a single
        // write-lock acquisition.
        let cancel_notify = Arc::new(ReconnectCancellation::default());
        let cancel_notify_clone = cancel_notify.clone();
        state
            .upsert_session(&id, |s| {
                s.reconnect_config = Some(ReconnectConfig {
                    host: host.clone(),
                    port,
                    user: user.clone(),
                    password: password.clone(),
                    private_key: private_key.clone(),
                    passphrase: passphrase.clone(),
                    auth_type: auth_type.clone(),
                    agent_forwarding: agent_forwarding.unwrap_or(false),
                    jump_hosts: jump_hosts.clone().unwrap_or_default(),
                    auto_login_rules: auto_login_rules.clone().unwrap_or_default(),
                    post_connect_commands: post_connect_commands.clone().unwrap_or_default(),
                    reconnect_type: rt,
                    session_name: auraterm_reconnect_session_name(&id),
                    checked_existing_sessions: false,
                    cols,
                    rows,
                    last_error: None,
                });
                s.reconnect_flag = Some(cancel_notify_clone);
            })
            .await;

        let state_clone = state.inner().clone();
        let zmodem_clone = zmodem.inner().clone();
        let app_clone = app.clone();
        let id_clone = id.clone();

        drop(auth_response_rx); // will be recreated fresh each reconnect attempt
        tokio::spawn(async move {
            run_reconnect_loop(
                app_clone,
                state_clone,
                zmodem_clone,
                id_clone,
                cancel_notify,
            ).await;
        });

        Ok(())
    } else {
        // Single-shot connection (no reconnect).
        // For Manual/Simple mode, no multiplexer is needed even in single-shot mode.
        let mux_type = match rt {
            ReconnectType::Manual => None,
            ReconnectType::Simple => None,
            other => Some(other),
        };
        let result = do_single_ssh_connect(
            app.clone(),
            state.inner().clone(),
            zmodem.inner().clone(),
            id.clone(),
            host.clone(),
            port,
            user.clone(),
            password.clone(),
            private_key.clone(),
            passphrase.clone(),
            auth_type.clone(),
            agent_forwarding.unwrap_or(false),
            jump_hosts.unwrap_or_default(),
            auto_login_rules.unwrap_or_default(),
            post_connect_commands.unwrap_or_default(),
            cols,
            rows,
            mux_type,
            None,
            false,
            auth_response_rx,
        ).await;

        match result {
            Ok(_rx) => Ok(()),
            Err(err) => {
                cleanup_ssh_session(state.inner(), &id).await;
                Err(err)
            }
        }
    }
}

/// The reconnect loop: keeps trying to connect every 5 seconds until cancelled.
async fn run_reconnect_loop(
    app: AppHandle,
    state: SshState,
    zmodem: crate::zmodem::ZmodemState,
    id: String,
    cancel_notify: Arc<ReconnectCancellation>,
) {
    let mut first_attempt = true;

    loop {
        // Check for cancellation before each attempt.
        if cancel_notify.is_cancelled() {
            break;
        }

        if !first_attempt {
            // Get the last error if available
            let last_error = state
                .with_session_mut(&id, |s| {
                    s.reconnect_config.as_mut().and_then(|c| c.last_error.take())
                })
                .await
                .flatten();

            let notice = if let Some(err) = last_error {
                format!("\r\n\x1b[31m[Disconnected: {err}]\x1b[0m\r\n\x1b[33m[Reconnecting in 5 s...]\x1b[0m\r\n")
            } else {
                "\r\n\x1b[33m[Disconnected; reconnecting in 5 s...]\x1b[0m\r\n".to_string()
            };

            // Emit a notice to the terminal.
            let _ = app.emit(
                &crate::util::session_event("pty-output", &id),
                TerminalDataPayload {
                    id: id.clone(),
                    data: notice,
                },
            );

            // Wait 5 seconds, but abort early if cancelled.
            tokio::select! {
                _ = tokio::time::sleep(tokio::time::Duration::from_secs(5)) => {}
                _ = cancel_notify.notify.clone().notified_owned() => { break; }
            }

            if cancel_notify.is_cancelled() {
                break;
            }
        }
        first_attempt = false;

        // Retrieve the latest reconnect config (cols/rows may have been updated by resize).
        let cfg = match state.reconnect_config(&id).await {
            Some(c) => c,
            None => break,
        };

        // Ensure a fresh auth-response channel is available.
        let (auth_tx, rx) = mpsc::channel::<String>(4);
        state
            .upsert_session(&id, |s| s.auth_tx = Some(auth_tx))
            .await;

        // For Manual/Simple mode, pass None as reconnect_type so no multiplexer is used.
        let mux_type = match cfg.reconnect_type {
            ReconnectType::Manual => None,
            ReconnectType::Simple => None,
            other => Some(other),
        };
        let result = do_single_ssh_connect(
            app.clone(),
            state.clone(),
            zmodem.clone(),
            id.clone(),
            cfg.host.clone(),
            cfg.port,
            cfg.user.clone(),
            cfg.password.clone(),
            cfg.private_key.clone(),
            cfg.passphrase.clone(),
            cfg.auth_type.clone(),
            cfg.agent_forwarding,
            cfg.jump_hosts.clone(),
            cfg.auto_login_rules.clone(),
            cfg.post_connect_commands.clone(),
            cfg.cols,
            cfg.rows,
            mux_type,
            Some(cfg.session_name.clone()),
            !cfg.checked_existing_sessions,
            rx,
        ).await;

        match result {
            Ok(_new_rx) => {
                // Connection is running; wait until it drops (cleanup_ssh_session removes handles).
                // Poll until the handle is gone or we're cancelled.
                loop {
                    tokio::select! {
                        _ = tokio::time::sleep(tokio::time::Duration::from_millis(500)) => {
                            let gone = state.handle(&id).await.is_none();
                            if gone { break; }
                        }
                        _ = cancel_notify.notify.clone().notified_owned() => { return; }
                    }
                }
            }
            Err(err) => {
                crate::debug_log!("[ssh-debug] {} do_single_ssh_connect returned Err: {}", id, err);
                cleanup_ssh_runtime_state(&state, &id).await;

                // Authentication errors are not recoverable by retrying with the
                // same stored credentials. Stop the reconnect loop and let the
                // frontend show the password-retry overlay via pty-exit.
                if is_auth_error(&err) {
                    cleanup_ssh_session(&state, &id).await;
                    let _ = app.emit(
                        &crate::util::session_event("pty-exit", &id),
                        PtyExitPayload {
                            id: id.clone(),
                            message: err,
                        },
                    );
                    return;
                }

                let _ = app.emit(
                    &crate::util::session_event("pty-output", &id),
                    TerminalDataPayload {
                        id: id.clone(),
                        data: format!("\r\n\x1b[31m[Reconnect failed: {}]\x1b[0m\r\n", err),
                    },
                );
            }
        }
    }

    // Loop exited — do final cleanup.
    cleanup_ssh_session(&state, &id).await;
    let _ = app.emit(
        &crate::util::session_event("pty-exit", &id),
        PtyExitPayload {
            id: id.clone(),
            message: "SSH session ended".to_string(),
        },
    );
}

/// Detect authentication-related error messages so the reconnect loop can
/// bail out instead of retrying with invalid credentials forever.
fn is_auth_error(err: &str) -> bool {
    let lower = err.to_lowercase();
    lower.contains("authentication failed")
        || lower.contains("auth failed")
        || lower.contains("incorrect password")
        || lower.contains("permission denied")
        || lower.contains("password authentication failed")
        || lower.contains("private key authentication failed")
}

/// Connect once to SSH, open a PTY, and spawn the IO loop.
/// Returns Ok(auth_response_rx) on success (ownership moved into caller for reuse),
/// or Err on failure.
fn do_single_ssh_connect(
    app: AppHandle,
    state: SshState,
    zmodem: crate::zmodem::ZmodemState,
    id: String,
    host: String,
    port: u16,
    user: String,
    password: Option<String>,
    private_key: Option<String>,
    passphrase: Option<String>,
    auth_type: Option<String>,
    agent_forwarding: bool,
    jump_hosts: Vec<JumpHostConfig>,
    auto_login_rules: Vec<AutoLoginRule>,
    post_connect_commands: Vec<String>,
    cols: u32,
    rows: u32,
    reconnect_type: Option<ReconnectType>,
    reconnect_session_name: Option<String>,
    should_prompt_existing_sessions: bool,
    mut auth_response_rx: mpsc::Receiver<String>,
) -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<mpsc::Receiver<String>, String>> + Send + 'static>> {
    Box::pin(async move {
    let addr = format!("{host}:{port}");
    crate::debug_log!("Connecting to {}...", addr);

    // Per-session remote-forward registry, reused across reconnects. Empty on a
    // fresh connect; populated once the user starts a remote (`-R`) tunnel.
    let remote_forwards = state.clone().ensure_remote_forwards_owned(id.clone()).await;
    let session_handle = authenticate_ssh(
        host.clone(),
        port,
        user.clone(),
        password.clone(),
        private_key.clone(),
        passphrase.clone(),
        auth_type.clone(),
        agent_forwarding,
        jump_hosts.clone(),
        app.clone(),
        id.clone(),
        &mut auth_response_rx,
        remote_forwards.clone(),
    )
    .await?;
    crate::debug_log!("[ssh-debug] {} authenticated; opening PTY channel", id);

    // Re-establish any remote (`-R`) forwards that survived a reconnect. The
    // server-side listener is lost when the transport drops, so re-issue the
    // `tcpip-forward` request for each registered bind port (no-op on a fresh
    // connect where the registry is empty).
    reissue_remote_forwards(session_handle.clone(), remote_forwards.clone()).await;

    crate::debug_log!("Requesting PTY and shell...");
    let mut selected_session_name = reconnect_session_name.unwrap_or_else(|| auraterm_reconnect_session_name(&id));

    if let Some(rt) = reconnect_type {
        let tool_name = match rt {
            ReconnectType::Manual => "",
            ReconnectType::Simple => "",
            ReconnectType::Tmux => "tmux",
            ReconnectType::Screen => "screen",
        };

        if should_prompt_existing_sessions {
            if remote_command_exists(session_handle.clone(), tool_name.to_string()).await {
                let sessions = list_detached_auraterm_sessions(session_handle.clone(), rt).await?;
                if let Some(existing_session) =
                    prompt_for_existing_reconnect_session(app.clone(), state.clone(), id.clone(), rt, sessions).await?
                {
                    selected_session_name = existing_session;
                }
            }

            set_reconnect_session_metadata(
                state.clone(),
                id.clone(),
                Some(selected_session_name.clone()),
                Some(true),
            )
            .await;
        }
    }

    let (channel, used_multiplexer) = open_pty_channel(
        session_handle.clone(),
        selected_session_name.clone(),
        cols,
        rows,
        reconnect_type,
        agent_forwarding,
    )
    .await?;

    if reconnect_type.is_some() {
        set_reconnect_session_metadata(state.clone(), id.clone(), Some(selected_session_name.clone()), None).await;
    }

    let (input_tx, input_rx) = mpsc::channel::<Vec<u8>>(512);
    let (resize_tx, resize_rx) = mpsc::channel::<(u32, u32)>(32);

    // Register all runtime channels/handles for this session in a single
    // write-lock acquisition.
    {
        let session_handle_entry = session_handle.clone();
        state.clone()
            .upsert_session_owned(id.clone(), move |s| {
                s.input_tx = Some(input_tx);
                s.resize_tx = Some(resize_tx);
                s.handle = Some(session_handle_entry);
            })
            .await;
    }

    let _ = app.emit(
        &crate::util::session_event("ssh-connected", &id),
        TerminalDataPayload { id: id.clone(), data: String::new() },
    );

    if !used_multiplexer {
        if let Some(rt) = reconnect_type {
            let tool = match rt {
                ReconnectType::Tmux => Some("tmux"),
                ReconnectType::Screen => Some("screen"),
                ReconnectType::Manual => None,
                ReconnectType::Simple => None,
            };
            if let Some(tool_name) = tool {
                let _ = app.emit(
                    &crate::util::session_event("pty-output", &id),
                    TerminalDataPayload {
                        id: id.clone(),
                        data: format!(
                            "\r\n\x1b[33m[Reconnect mode: {} not found on remote host, using plain shell]\x1b[0m\r\n",
                            tool_name
                        ),
                    },
                );
            }
        }
    }

    let connection_id = id;
    let app_handle = app;
    let state_clone = state;
    let session_handle_for_io = session_handle.clone();
    let automation_rules = auto_login_rules;
    let automation_commands = post_connect_commands;

    crate::debug_log!(
        "[ssh-debug] {} PTY channel established (used_multiplexer={}); entering IO loop",
        connection_id, used_multiplexer
    );

    tokio::spawn(async move {
        run_channel_io_loop(
            app_handle,
            state_clone,
            zmodem,
            connection_id,
            session_handle_for_io,
            channel,
            input_rx,
            resize_rx,
            automation_rules,
            automation_commands,
        )
        .await;
    });

    Ok(auth_response_rx)
    })
}

struct LoginAutomation {
    rules: Vec<AutoLoginRule>,
    next_rule: usize,
    buffer: String,
    post_connect_commands: Vec<String>,
    post_commands_sent: bool,
    deadline: tokio::time::Instant,
    cancelled: bool,
}

impl LoginAutomation {
    fn new(rules: Vec<AutoLoginRule>, post_connect_commands: Vec<String>) -> Self {
        let timeout = rules.first().map(|rule| rule.timeout_secs).unwrap_or(30).max(1);
        Self {
            rules,
            next_rule: 0,
            buffer: String::new(),
            post_connect_commands,
            post_commands_sent: false,
            deadline: tokio::time::Instant::now() + std::time::Duration::from_secs(timeout),
            cancelled: false,
        }
    }

    fn initial_inputs(&mut self) -> Vec<String> {
        if self.rules.is_empty() {
            return self.take_post_commands();
        }
        Vec::new()
    }

    fn on_output(&mut self, output: &str) -> Vec<String> {
        if !self.is_waiting() {
            return Vec::new();
        }
        self.buffer.push_str(output);
        if self.buffer.len() > 16 * 1024 {
            let mut keep_from = self.buffer.len() - 16 * 1024;
            while keep_from < self.buffer.len() && !self.buffer.is_char_boundary(keep_from) {
                keep_from += 1;
            }
            self.buffer.drain(..keep_from);
        }

        let rule = &self.rules[self.next_rule];
        let matched = if rule.case_sensitive {
            self.buffer.contains(&rule.expect)
        } else {
            self.buffer.to_lowercase().contains(&rule.expect.to_lowercase())
        };
        if !matched {
            return Vec::new();
        }

        let mut inputs = vec![line_input(rule.response.as_deref().unwrap_or_default())];
        self.next_rule += 1;
        self.buffer.clear();
        if self.next_rule < self.rules.len() {
            let timeout = self.rules[self.next_rule].timeout_secs.max(1);
            self.deadline = tokio::time::Instant::now() + std::time::Duration::from_secs(timeout);
        } else {
            inputs.extend(self.take_post_commands());
        }
        inputs
    }

    fn take_post_commands(&mut self) -> Vec<String> {
        if self.post_commands_sent {
            return Vec::new();
        }
        self.post_commands_sent = true;
        self.post_connect_commands
            .iter()
            .filter(|command| !command.trim().is_empty())
            .map(|command| line_input(command))
            .collect()
    }

    fn is_waiting(&self) -> bool {
        !self.cancelled && self.next_rule < self.rules.len()
    }

    fn deadline(&self) -> tokio::time::Instant {
        self.deadline
    }

    fn cancel(&mut self) {
        self.cancelled = true;
        self.buffer.clear();
    }
}

fn line_input(value: &str) -> String {
    if value.ends_with('\n') || value.ends_with('\r') {
        value.to_string()
    } else {
        format!("{value}\r")
    }
}

/// Drive the SSH channel: forward data to the frontend, forward input/resize to the channel.
async fn run_channel_io_loop(
    app: AppHandle,
    state: SshState,
    zmodem: crate::zmodem::ZmodemState,
    id: String,
    handle: SharedSshHandle,
    mut channel: russh::Channel<client::Msg>,
    mut input_rx: mpsc::Receiver<Vec<u8>>,
    mut resize_rx: mpsc::Receiver<(u32, u32)>,
    auto_login_rules: Vec<AutoLoginRule>,
    post_connect_commands: Vec<String>,
) {
    state.hub.publish(&id, &crate::terminal_event_hub::TerminalEvent::Reconnected);
    let mut last_write_error_notice_at: Option<std::time::Instant> = None;
    let final_exit_message;
    let loop_started_at = std::time::Instant::now();
    let mut data_bytes_total: u64 = 0;
    let mut data_msg_count: u64 = 0;
    // Separate decoders for stdout (Data) and stderr (ExtendedData) so an
    // incomplete multi-byte sequence on one stream is never spliced onto the
    // other. Each buffers trailing bytes of a UTF-8 char split across packets.
    let mut stdout_decoder = crate::util::Utf8StreamDecoder::new();
    let mut stderr_decoder = crate::util::Utf8StreamDecoder::new();
    let mut automation = LoginAutomation::new(auto_login_rules, post_connect_commands);

    for input in automation.initial_inputs() {
        let _ = write_interactive_input(&mut channel, &handle, input.as_bytes()).await;
    }

    crate::debug_log!("[ssh-debug] {} run_channel_io_loop started", id);

    loop {
        tokio::select! {
            msg = channel.wait() => {
                match msg {
                    Some(ChannelMsg::Data { ref data }) => {
                        state.hub.publish(&id, &crate::terminal_event_hub::TerminalEvent::Output(data.to_vec()));
                        data_msg_count += 1;
                        data_bytes_total += data.len() as u64;
                        let (output, response) = crate::util::pump_stream_chunk(
                            &app,
                            &id,
                            &mut stdout_decoder,
                            data,
                            &zmodem,
                        );
                        if !response.is_empty() {
                            let _ = write_interactive_input(&mut channel, &handle, &response).await;
                        }
                        if !output.is_empty() {
                            for input in automation.on_output(&output) {
                                let _ = write_interactive_input(&mut channel, &handle, input.as_bytes()).await;
                            }
                        }
                    }
                    Some(ChannelMsg::ExtendedData { ref data, ext }) => {
                        state.hub.publish(&id, &crate::terminal_event_hub::TerminalEvent::Output(data.to_vec()));
                        data_msg_count += 1;
                        data_bytes_total += data.len() as u64;
                        crate::debug_log!(
                            "[ssh-debug] {} ExtendedData ext={} ({} bytes)",
                            id, ext, data.len()
                        );
                        let output = stderr_decoder.push(data);
                        if !output.is_empty() {
                            let _ = app.emit(
                                &crate::util::session_event("pty-output", &id),
                                TerminalDataPayload {
                                    id: id.clone(),
                                    data: output.clone(),
                                },
                            );
                            for input in automation.on_output(&output) {
                                let _ = write_interactive_input(&mut channel, &handle, input.as_bytes()).await;
                            }
                        }
                    }
                    Some(ChannelMsg::Eof) => {
                        crate::debug_log!(
                            "[ssh-debug] {} received ChannelMsg::Eof after {:?} (msgs={}, bytes={})",
                            id, loop_started_at.elapsed(), data_msg_count, data_bytes_total
                        );
                        final_exit_message = Some("SSH connection closed by remote (EOF)".to_string());
                        break;
                    }
                    Some(ChannelMsg::Close) => {
                        crate::debug_log!(
                            "[ssh-debug] {} received ChannelMsg::Close after {:?} (msgs={}, bytes={})",
                            id, loop_started_at.elapsed(), data_msg_count, data_bytes_total
                        );
                        final_exit_message = Some("SSH connection closed by remote (Close)".to_string());
                        break;
                    }
                    Some(ChannelMsg::ExitStatus { exit_status }) => {
                        crate::debug_log!(
                            "[ssh-debug] {} received ExitStatus={} after {:?}",
                            id, exit_status, loop_started_at.elapsed()
                        );
                    }
                    Some(ChannelMsg::ExitSignal { ref signal_name, core_dumped, ref error_message, ref lang_tag }) => {
                        crate::debug_log!(
                            "[ssh-debug] {} received ExitSignal signal={:?} core_dumped={} error={:?} lang={:?}",
                            id, signal_name, core_dumped, error_message, lang_tag
                        );
                        final_exit_message = Some(format!(
                            "SSH remote shell killed by signal {:?}: {}",
                            signal_name, error_message
                        ));
                        break;
                    }
                    Some(ChannelMsg::Success) => {
                        // Normal reply to a channel request (e.g. pty-req / shell). Ignore.
                    }
                    Some(ChannelMsg::Failure) => {
                        crate::debug_log!("[ssh-debug] {} received ChannelMsg::Failure (server rejected a channel request)", id);
                    }
                    Some(ChannelMsg::OpenFailure(reason)) => {
                        crate::debug_log!("[ssh-debug] {} received ChannelMsg::OpenFailure: {:?}", id, reason);
                        final_exit_message = Some(format!("SSH channel open failure: {:?}", reason));
                        break;
                    }
                    Some(other) => {
                        // Log unknown / unhandled ChannelMsg variants to diagnose unexpected disconnects.
                        crate::debug_log!(
                            "[ssh-debug] {} unhandled ChannelMsg variant: {:?}",
                            id, std::mem::discriminant(&other)
                        );
                    }
                    None => {
                        crate::debug_log!(
                            "[ssh-debug] {} channel.wait() returned None after {:?} (msgs={}, bytes={}); likely transport closed (keepalive timeout or TCP reset)",
                            id, loop_started_at.elapsed(), data_msg_count, data_bytes_total
                        );
                        final_exit_message = Some("SSH channel closed (transport ended)".to_string());
                        break;
                    }
                }
            }
            Some(input) = input_rx.recv() => {
                match write_interactive_input(&mut channel, &handle, input.as_slice()).await {
                    InteractiveWriteOutcome::Sent => {}
                    InteractiveWriteOutcome::Dropped(message) => {
                        crate::debug_log!("[ssh-debug] {} write dropped: {}", id, message);
                        let should_emit = last_write_error_notice_at
                            .map(|t| t.elapsed() >= std::time::Duration::from_secs(2))
                            .unwrap_or(true);
                        if should_emit {
                            last_write_error_notice_at = Some(std::time::Instant::now());
                            let _ = app.emit(
                                &crate::util::session_event("pty-output", &id),
                                TerminalDataPayload {
                                    id: id.clone(),
                                    data: format!("\r\n\x1b[33m[{message}]\x1b[0m\r\n"),
                                },
                            );
                        }
                    }
                }
            }
            Some((c, r)) = resize_rx.recv() => {
                let _ = channel.window_change(c, r, 0, 0).await;
                // Keep cols/rows up-to-date for reconnect.
                state
                    .with_session_mut(&id, |s| {
                        if let Some(cfg) = s.reconnect_config.as_mut() {
                            cfg.cols = c;
                            cfg.rows = r;
                        }
                    })
                    .await;
            }
            _ = tokio::time::sleep_until(automation.deadline()), if automation.is_waiting() => {
                automation.cancel();
                let _ = app.emit(
                    &crate::util::session_event("pty-output", &id),
                    TerminalDataPayload {
                        id: id.clone(),
                        data: "\r\n\x1b[33m[Login automation timed out; continuing interactively]\x1b[0m\r\n".to_string(),
                    },
                );
            }
            else => {
                crate::debug_log!("[ssh-debug] {} select!/else branch hit — all sources closed", id);
                final_exit_message = Some("Interactive IO loop ended unexpectedly".to_string());
                break;
            }
        }
    }

    crate::debug_log!(
        "[ssh-debug] {} IO loop exit after {:?}; final_message={:?}; msgs={}, bytes={}",
        id,
        loop_started_at.elapsed(),
        final_exit_message,
        data_msg_count,
        data_bytes_total
    );

    // Connection dropped — drop transient handles so the reconnect loop detects it,
    // and update the last-error in a single write-lock acquisition.
    let has_reconnect = {
        let mut guard = state.sessions.write().await;
        match guard.get_mut(&id) {
            Some(s) => {
                s.input_tx = None;
                s.resize_tx = None;
                s.handle = None;
                if let Some(ref msg) = final_exit_message {
                    if let Some(cfg) = s.reconnect_config.as_mut() {
                        cfg.last_error = Some(msg.clone());
                    }
                }
                s.reconnect_flag.is_some()
            }
            None => false,
        }
    };
    if !has_reconnect {
        let message = final_exit_message.clone().unwrap_or_else(|| "SSH connection closed".to_string());
        state.hub.publish(&id, &crate::terminal_event_hub::TerminalEvent::Exit(message));
        let _ = app.emit(
            &crate::util::session_event("pty-exit", &id),
            PtyExitPayload {
                id: id.clone(),
                message: final_exit_message.unwrap_or_else(|| "SSH connection closed".to_string()),
            },
        );
    } else {
        state.hub.publish(&id, &crate::terminal_event_hub::TerminalEvent::Disconnected(
            final_exit_message.unwrap_or_else(|| "SSH connection interrupted".to_string())));
    }
}

/// Try to write interactive input to the SSH channel.
///
/// **Important**: We intentionally do NOT cancel / abort `channel.data()` via a
/// short timeout.  In russh the channel internally manages an SSH window; when
/// the window is full (fast typing / slow consumer) the write future blocks
/// until the server sends a window-adjust.  Cancelling the future mid-flight
/// corrupts the channel and produces "channel closed" errors on subsequent
/// writes — which is exactly the bug the user reported.
///
/// Any write error here is treated as non-fatal for session lifetime.
/// We keep the read loop alive and wait for explicit `Eof`/`Close` from the
/// remote side before exiting, which avoids false session exits.
async fn write_interactive_input(
    channel: &mut russh::Channel<client::Msg>,
    _handle: &SharedSshHandle,
    input_bytes: &[u8],
) -> InteractiveWriteOutcome {
    match channel.data(input_bytes).await {
        // Write succeeded — everything is fine.
        Ok(()) => InteractiveWriteOutcome::Sent,

        // Do not terminate the whole session on a single write failure.
        // If the session is really gone, channel.wait() will soon emit Close/Eof.
        Err(error) => InteractiveWriteOutcome::Dropped(format!(
            "SSH write failed: {error}; input dropped"
        )),
    }
}

/// Export the trusted SSH host-key fingerprints (`"host:port" -> "SHA256:..."`)
/// as a flat map, for inclusion in an encrypted cloud-sync bundle.
pub async fn export_known_hosts(app: &AppHandle) -> Result<HashMap<String, String>, String> {
    Ok(known_hosts::load_known_hosts(app).await?.hosts)
}

/// Merge synced host-key fingerprints into the local trust store. Local entries
/// always win on conflict — sync must never silently override a fingerprint that
/// was trusted on this device. Returns the number of newly added entries.
pub async fn import_known_hosts(
    app: &AppHandle,
    incoming: HashMap<String, String>,
) -> Result<usize, String> {
    let mut store = known_hosts::load_known_hosts(app).await?;
    let mut added = 0usize;
    for (scope, fingerprint) in incoming {
        if !store.hosts.contains_key(&scope) {
            store.hosts.insert(scope, fingerprint);
            added += 1;
        }
    }
    known_hosts::save_known_hosts(app, &store).await?;
    Ok(added)
}

#[cfg(test)]
mod tests {
    use super::known_hosts::{known_host_scope, parse_known_host_scope, summarize_fingerprint};
    use super::{
        auraterm_reconnect_session_name, build_screen_attach_command, build_tmux_attach_command,
        is_auth_error, shell_escape, ssh_generate_key_pair, AutoLoginRule, LoginAutomation,
        ReconnectType, AURATERM_RECONNECT_SESSION_PREFIX,
    };

    #[test]
    fn shell_escape_handles_single_quotes() {
        assert_eq!(shell_escape("a'b"), "'a'\"'\"'b'");
    }

    #[test]
    fn build_tmux_attach_command_prefers_existing_session() {
        let command = build_tmux_attach_command("at-tab-0");
        // Session name must be shell-escaped, and the order must be
        // attach-or-create → enable mouse.
        assert!(command.contains("tmux new-session -A -s 'at-tab-0'"));
        assert!(command.contains("tmux attach-session -t 'at-tab-0'"));
        assert!(command.contains("tmux set -g mouse on"));
        let attach_or_create = command.find("new-session -A").unwrap();
        let mouse = command.find("mouse on").unwrap();
        assert!(attach_or_create < mouse, "attach must come before enabling mouse");
    }

    #[test]
    fn build_tmux_attach_command_escapes_session_name() {
        let command = build_tmux_attach_command("evil'; rm -rf /");
        // The injected quote must be escaped, never passed through raw.
        assert!(command.contains("'evil'\"'\"'; rm -rf /'"));
    }

    #[test]
    fn build_screen_attach_command_prefers_known_screen_terms() {
        let command = build_screen_attach_command("demo");

        assert!(command.contains("screen.xterm-256color"));
        assert!(command.contains("screen-256color"));
        assert!(command.contains("screen -T \"$screen_term\" -dr"));
        assert!(command.contains("\"term $screen_term\""));
    }

    // ---------------------------------------------------------------------
    // known_hosts scope (host:port ←→ string) — round-trip parsing
    // ---------------------------------------------------------------------

    #[test]
    fn known_host_scope_round_trips_ipv4_and_hostname() {
        let cases = [
            ("example.com", 22u16),
            ("10.0.0.1", 2222u16),
            ("host-with-dash.internal", 65535u16),
        ];

        for (host, port) in cases {
            let scope = known_host_scope(host, port);
            assert_eq!(scope, format!("{host}:{port}"));

            let parsed = parse_known_host_scope(&scope).expect("scope should parse");
            assert_eq!(parsed, (host.to_string(), port));
        }
    }

    #[test]
    fn parse_known_host_scope_handles_ipv6_with_port_suffix() {
        // rsplit_once(':') intentionally splits on the last colon, which is
        // exactly how `host:port` is preserved even for bracketed IPv6.
        let scope = known_host_scope("[fe80::1]", 22);
        assert_eq!(scope, "[fe80::1]:22");
        let parsed = parse_known_host_scope(&scope).expect("scope should parse");
        assert_eq!(parsed, ("[fe80::1]".to_string(), 22u16));
    }

    #[test]
    fn parse_known_host_scope_rejects_invalid_input() {
        // Missing port
        assert!(parse_known_host_scope("example.com").is_none());
        // Non-numeric port
        assert!(parse_known_host_scope("example.com:http").is_none());
        // Port out of u16 range
        assert!(parse_known_host_scope("example.com:70000").is_none());
        // Empty string
        assert!(parse_known_host_scope("").is_none());
    }

    #[test]
    fn summarize_fingerprint_shortens_long_values() {
        let long = "SHA256:1234567890abcdefghijklmnopqrstuvwxyz1234567890ABCDEF";
        let short = summarize_fingerprint(long);
        assert!(short.contains("..."));
        assert!(short.len() < long.len());
    }

    #[test]
    fn summarize_fingerprint_leaves_short_values_intact() {
        let short = "SHA256:abcdef";
        assert_eq!(summarize_fingerprint(short), short);
    }

    // ---------------------------------------------------------------------
    // Reconnect state machine helpers
    // ---------------------------------------------------------------------

    #[test]
    fn auraterm_reconnect_session_name_uses_known_prefix() {
        let name = auraterm_reconnect_session_name("abc-123");
        assert!(name.starts_with(AURATERM_RECONNECT_SESSION_PREFIX));
        assert_eq!(name, format!("{AURATERM_RECONNECT_SESSION_PREFIX}abc-123"));
    }

    #[test]
    fn is_auth_error_detects_common_messages() {
        assert!(is_auth_error("Authentication failed"));
        assert!(is_auth_error("SSH: auth failed"));
        assert!(is_auth_error("Incorrect password"));
        assert!(is_auth_error("Permission denied (publickey,password)."));
        assert!(is_auth_error("password authentication failed"));
        assert!(is_auth_error("private key authentication failed"));
        // case-insensitive match
        assert!(is_auth_error("PERMISSION DENIED"));
    }

    #[test]
    fn is_auth_error_ignores_transient_failures() {
        // These are precisely the cases where the reconnect loop MUST keep retrying.
        assert!(!is_auth_error("connection refused"));
        assert!(!is_auth_error("no route to host"));
        assert!(!is_auth_error("timed out"));
        assert!(!is_auth_error("connection reset by peer"));
        assert!(!is_auth_error(""));
    }

    #[test]
    fn reconnect_type_serializes_lowercase() {
        let manual = serde_json::to_string(&ReconnectType::Manual).unwrap();
        let simple = serde_json::to_string(&ReconnectType::Simple).unwrap();
        let screen = serde_json::to_string(&ReconnectType::Screen).unwrap();
        let tmux = serde_json::to_string(&ReconnectType::Tmux).unwrap();

        assert_eq!(manual, "\"manual\"");
        assert_eq!(simple, "\"simple\"");
        assert_eq!(screen, "\"screen\"");
        assert_eq!(tmux, "\"tmux\"");
    }

    #[test]
    fn reconnect_type_roundtrips_from_frontend_strings() {
        // The frontend emits the lowercase tag; ensure backend accepts exactly those.
        for raw in ["manual", "simple", "screen", "tmux"] {
            let quoted = format!("\"{raw}\"");
            let parsed: ReconnectType = serde_json::from_str(&quoted)
                .unwrap_or_else(|e| panic!("failed to parse {raw}: {e}"));

            // Round-trip back through Serialize and confirm we end where we started.
            let re_encoded = serde_json::to_string(&parsed).unwrap();
            assert_eq!(re_encoded, quoted);
        }
    }

    #[test]
    fn reconnect_type_rejects_unknown_variant() {
        assert!(serde_json::from_str::<ReconnectType>("\"bogus\"").is_err());
        assert!(serde_json::from_str::<ReconnectType>("\"Manual\"").is_err()); // case sensitive
    }

    #[test]
    fn login_automation_runs_rules_in_order_then_commands() {
        let rules = vec![
            AutoLoginRule {
                expect: "login:".to_string(),
                response: Some("admin".to_string()),
                case_sensitive: false,
                timeout_secs: 30,
            },
            AutoLoginRule {
                expect: "Password:".to_string(),
                response: Some("secret".to_string()),
                case_sensitive: true,
                timeout_secs: 30,
            },
        ];
        let mut automation = LoginAutomation::new(rules, vec!["enable".to_string()]);

        assert!(automation.on_output("LOGIN:").contains(&"admin\r".to_string()));
        assert!(automation.on_output("password:").is_empty());
        assert_eq!(
            automation.on_output("Password:"),
            vec!["secret\r".to_string(), "enable\r".to_string()]
        );
        assert!(!automation.is_waiting());
    }

    #[test]
    fn login_automation_without_expect_rules_runs_commands_immediately() {
        let mut automation = LoginAutomation::new(
            Vec::new(),
            vec!["whoami".to_string(), "".to_string()],
        );
        assert_eq!(automation.initial_inputs(), vec!["whoami\r".to_string()]);
        assert!(automation.initial_inputs().is_empty());
    }

    #[test]
    fn generated_ed25519_key_uses_the_separate_passphrase() {
        let generated = ssh_generate_key_pair(
            Some("key-passphrase".to_string()),
            Some("alice@example".to_string()),
        ).expect("key generation should succeed");

        assert!(generated.private_key.contains("OPENSSH PRIVATE KEY"));
        assert!(generated.public_key.starts_with("ssh-ed25519 "));
        assert!(generated.public_key.ends_with(" alice@example"));
        assert!(russh::keys::decode_secret_key(&generated.private_key, Some("key-passphrase")).is_ok());
        assert!(russh::keys::decode_secret_key(&generated.private_key, Some("wrong")).is_err());
    }

}
