#!/usr/bin/env python3
"""Sync Changelog.md into the AuraXLabs site checkout.

The site renders /products/auraterm/changelog from a copy of this repo's
Changelog.md (AuraXLabs/app/data/auraterm_changelog.md). This script
refreshes that copy so ``make release`` keeps the site's changelog current.

The AuraXLabs checkout is looked for next to this repo (../AuraXLabs) unless
AURAXLABS_DIR says otherwise. A missing checkout is a warning, not an error:
release builds also run on machines that only have AuraTerm.
"""

import json
import os
import sys
from pathlib import Path

HEADER = (
    "<!-- Auto-generated copy of AuraTerm/Changelog.md - do not edit here. "
    "Regenerated by AuraTerm's `make release` (scripts/sync_changelog.py). "
    "Rendered at /products/auraterm/changelog. -->\n\n"
)


def main():
    changelog = Path("Changelog.md")
    if not changelog.exists():
        print("Error: Changelog.md not found (run from the repo root)")
        return 1
    text = changelog.read_text(encoding="utf-8")

    # A release whose version has no changelog entry would render a site
    # changelog that silently stops one version short.
    version = json.loads(
        Path("package.json").read_text(encoding="utf-8")).get("version", "")
    if version and "## %s" % version not in text:
        print("Warning: Changelog.md has no '## %s' entry for the version "
              "being released" % version)

    site_dir = Path(os.environ.get("AURAXLABS_DIR") or Path("..") / "AuraXLabs")
    target = site_dir / "app" / "data" / "auraterm_changelog.md"
    if not target.parent.is_dir():
        print("Warning: AuraXLabs checkout not found at %s; "
              "site changelog NOT refreshed" % site_dir)
        print("         (set AURAXLABS_DIR, or copy Changelog.md to "
              "app/data/auraterm_changelog.md by hand)")
        return 0

    content = HEADER + text
    if target.exists() and target.read_text(encoding="utf-8") == content:
        print("Site changelog already up to date: %s" % target)
        return 0
    target.write_text(content, encoding="utf-8")
    print("Site changelog refreshed: %s (commit it in AuraXLabs to publish)"
          % target)
    return 0


if __name__ == "__main__":
    sys.exit(main())
