#!/usr/bin/env python3
"""Sync this repo's release facts into the AuraXLabs site checkout.

The site renders two things that live in *this* repo:

* ``/docs/changelog`` comes from a copy of ``Changelog.md``
  (``AuraXLabs/app/data/auraterm_changelog.md``).
* The current version — the homepage's "AuraTerm 当前版本", the product
  page's release pill, and the line the changelog page draws between
  released and 开发中 entries — comes from ``package.json``'s version,
  written out as ``AuraXLabs/app/data/auraterm_release.json``.

Both used to be hand-maintained on the site side, and the version in
particular was a config literal that every release had to remember to bump.
``make release`` regenerates both from this repo, which is the only place
that actually knows what shipped.

The AuraXLabs checkout is looked for next to this repo (../AuraXLabs) unless
AURAXLABS_DIR says otherwise. A missing checkout is a warning, not an error:
release builds also run on machines that only have AuraTerm.
"""

import json
import os
import sys
from pathlib import Path

CHANGELOG_HEADER = (
    "<!-- Auto-generated copy of AuraTerm/Changelog.md - do not edit here. "
    "Regenerated by AuraTerm's `make release` (scripts/sync_site.py). "
    "Rendered at /docs/changelog. -->\n\n"
)

RELEASE_PIN_COMMENT = (
    "Auto-generated by AuraTerm's `make release` (scripts/sync_site.py) from "
    "package.json - do not edit here. Read by AuraXLabs config.py as "
    "AURATERM_LATEST_VERSION; the env var of the same name still wins."
)


def site_data_dir(site_dir):
    """Return the site's app/data directory, or None if the checkout is absent.

    Absent means "this machine only has AuraTerm checked out", which is a
    normal state for a build box — not a release failure.
    """
    data_dir = Path(site_dir) / "app" / "data"
    return data_dir if data_dir.is_dir() else None


def render_changelog(text):
    """Return the exact bytes the site's changelog copy should contain."""
    return CHANGELOG_HEADER + text


def render_release_pin(version):
    """Return the exact bytes the site's release-pin file should contain.

    Trailing newline included: the file is committed to the site repo, and a
    no-newline-at-end-of-file diff on every release is pure noise.
    """
    return json.dumps(
        {"_comment": RELEASE_PIN_COMMENT, "latest_version": version},
        indent=2,
        ensure_ascii=False,
    ) + "\n"


def write_if_changed(target, content):
    """Write ``content`` to ``target`` unless it is already there.

    Returns True when the file was written. Skipping an identical write keeps
    the site checkout free of no-op modifications, so ``git status`` there
    only ever shows a release that actually changed something.
    """
    if target.exists() and target.read_text(encoding="utf-8") == content:
        return False
    target.write_text(content, encoding="utf-8")
    return True


def read_repo_version(package_json=Path("package.json")):
    """Return the version package.json declares, or '' if it says nothing."""
    try:
        data = json.loads(Path(package_json).read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return ""
    version = data.get("version")
    return version if isinstance(version, str) else ""


def main():
    changelog = Path("Changelog.md")
    if not changelog.exists():
        print("Error: Changelog.md not found (run from the repo root)")
        return 1
    text = changelog.read_text(encoding="utf-8")

    version = read_repo_version()
    if not version:
        print("Error: package.json declares no version")
        return 1

    # A release whose version has no changelog entry would render a site
    # changelog that silently stops one version short.
    if "## %s" % version not in text:
        print("Warning: Changelog.md has no '## %s' entry for the version "
              "being released" % version)

    site_dir = Path(os.environ.get("AURAXLABS_DIR") or Path("..") / "AuraXLabs")
    data_dir = site_data_dir(site_dir)
    if data_dir is None:
        print("Warning: AuraXLabs checkout not found at %s; site changelog "
              "and version pin NOT refreshed" % site_dir)
        print("         (set AURAXLABS_DIR, or update app/data/"
              "auraterm_changelog.md and auraterm_release.json by hand)")
        return 0

    wrote_any = False
    for target, content, label in (
        (data_dir / "auraterm_changelog.md", render_changelog(text),
         "changelog"),
        (data_dir / "auraterm_release.json", render_release_pin(version),
         "version pin (%s)" % version),
    ):
        if write_if_changed(target, content):
            print("Site %s refreshed: %s" % (label, target))
            wrote_any = True
        else:
            print("Site %s already up to date: %s" % (label, target))

    if wrote_any:
        print("Commit the changes in AuraXLabs to publish them.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
